// angular-app/src/app/components/modal-atualizar/modal-atualizar.component.ts
import { Component, OnInit, TemplateRef, Input } from '@angular/core';
import { BsModalRef, BsModalService } from 'ngx-bootstrap/modal';
import { Tarefa } from 'src/app/tarefas/shared/tarefa';
import { TarefaService } from 'src/app/tarefas/shared/tarefa.service';

@Component({
  selector: 'app-modal-atualizar',
  templateUrl: './modal-atualizar.component.html',
  styleUrls: ['./modal-atualizar.component.css']
})
export class ModalAtualizarComponent implements OnInit{
  modalRef!: BsModalRef;
  @Input() item!: Tarefa;
  constructor(private modalService: BsModalService, private tarefaService: TarefaService) {}

  openModal(template: TemplateRef<any>) {
    this.modalRef = this.modalService.show(template);
  }

  ngOnInit(): void {
  }

  updateItem(): void {
    const inicio = Date.now();

    if (!this.item || !this.item.key) {
      console.error('Item inválido para atualização');
      return;
    }
    this.tarefaService.update(this.item.key, this.item)
      .then(() => {
        console.log('Atividade atualizada com sucesso!');
        this.modalRef.hide();
        const fim = Date.now();
        const tempoResposta = fim - inicio;
        console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
      })
      .catch(error => {
        console.error('Ocorreu um erro ao atualizar a atividade:', error);
      });
  }

}

<button type="button" class="btn btn-success" id="show-btn" (click)="openModal(template)"><i class="bi bi-pencil-fill"></i></button>

<ng-template #template>
   <div class="modal-header">
      <h4 class="modal-title pull-left">Atualizar Atividade</h4>
      <button type="button" class="close pull-right" aria-label="Close" (click)="modalRef.hide()">
         <span aria-hidden="true">×</span>
      </button>
   </div>
   <div class="modal-body">
    <div class="text-center">
      <form >
        <div class="form-group" id="input-group-1" style="margin-top: 0.5rem">
          <label for="InputTitle">Título da Atividade</label>
          <input type="text" class="form-control" id="InputTitle" placeholder="Título da Atividade">
        </div>

        <div class="form-group" id="input-group-2" style="margin-top: 0.5rem">
          <label for="exampleInputPassword1">Descrição</label>
          <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Descrição">
        </div>

        <div class="row">
          <div class="col">
            <label for="data">Data</label>
            <input type="date" class="form-control" id="data "placeholder="Nome">
          </div>
          <div class="col">
            <label for="hora">Hora</label>
            <input type="time" class="form-control" id="hora" placeholder="Sobrenome">
          </div>
        </div>
      </form>
    </div>
  </div>
   <div class="modal-footer">
      <button type="button" class="btn btn-success">Cadastrar</button>
      <button type="button" class="btn btn-danger" (click)="modalRef.hide()">Cancelar</button>
   </div>
</ng-template>

// react-app/src/components/ModalAtualizar/index.js
import React, { useState,useEffect } from 'react';
import { Modal, Button,Row,Col,Form } from 'react-bootstrap';
import DataService from "../../services/service";


export default function ModalAtualizar(props){

  const {id, tarefa} = props;

  const [atividade, setAtividade] = useState(false);

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [date, setDate] = useState('');
  const [time, setTime] = useState('');

  useEffect(() => {

      setTitle(tarefa.title);
      setDescription(tarefa.description);
      setDate(tarefa.date);
      setTime(tarefa.time);

  }, []);

  const updateTutorial = () =>{
    const inicio = Date.now();
    const data = {
      title: title,
      description: description,
      date: date,
      time: time,
    };

    DataService.update(id, data)
      .then(() => {
          console.log("Atualizado com sucesso!");
          setAtividade(false);
          const fim = Date.now();
          const tempoResposta = fim - inicio;
          console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
      })
      .catch((e) => {
        console.log(e);
      });

  }
  
  return (
    <>
      <Button variant="success" size="sm" onClick={(a) => setAtividade(true) }> <i className="fas fa-pen"></i></Button>

      <Modal show={atividade} onHide={() => setAtividade(false)}>

        <Modal.Header>
          <Modal.Title>Atualizar Atividade</Modal.Title>
        </Modal.Header>

        <Modal.Body>
          <Row>
              <Col>
                <Form.Row>
                  <Form.Group as={Col} controlId="descriçãoAtvId">
                    <Form.Label>Titulo da atividade</Form.Label>
                    <Form.Control type="text" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Titulo da atividade" required/>
                  </Form.Group>
                </Form.Row>
              </Col>
          </Row>
          <Row>
              <Col>
                <Form.Row>
                  <Form.Group as={Col} controlId="descriçãoAtvId">
                    <Form.Label>Descrição</Form.Label>
                    <Form.Control type="text" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Descrição da atividade" required/>
                  </Form.Group>
                </Form.Row>
              </Col>
          </Row>
          <Row>
              <Col sm={6} >
                <Form.Row>
                  <Form.Group as={Col} controlId="descriçãoAtvId">
                    <Form.Label>Data</Form.Label>
                    <Form.Control type="date" value={date} onChange={(e) => setDate(e.target.value)} placeholder="Data da atividade" required/>
                  </Form.Group>
                </Form.Row>
              </Col>
              <Col sm={6} >
                <Form.Row>
                  <Form.Group as={Col} controlId="descriçãoAtvId">
                    <Form.Label>Hora</Form.Label>
                    <Form.Control type="time" value={time} onChange={(e) => setTime(e.target.value)} placeholder="Hora da atividade" required/>
                  </Form.Group>
                </Form.Row>
              </Col>
          </Row>
          
        </Modal.Body>

        <Modal.Footer>
          <Button variant="danger" onClick={() => setAtividade(false)}> Cancelar </Button>
          <Button variant="success" onClick={() => updateTutorial()}>  Atualizar </Button>
        </Modal.Footer>
      </Modal>
    </>
  );


}
