// react-app/src/pages/Login/index.js
import React, { useState } from "react";
import { Container, Button, Card, Form } from "react-bootstrap";

import { firebase } from '@firebase/app'
import "firebase/auth";

import "./style.css"
<script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-auth.js"></script>


export default function Login({ history }) {

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const loginUser = () => {
        const inicio = Date.now();
        firebase.auth().signInWithEmailAndPassword(email, password).then(function (userCredential) {
            var user = userCredential.user;
            history.push(`/list`);
            const fim = Date.now();
            const tempoResposta = fim - inicio;
            console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);

        }).catch(function (error) {
            // Handle Errors here.
            var errorCode = error.code;
            var errorMessage = error.message;
            if (errorCode === 'auth/wrong-password') {
                alert('Wrong password.');
            } else {
                alert(errorMessage);
            }
            console.log(error);
        });

    }

    const CadastrarUser = () => {
        const inicio = Date.now();
        firebase.auth().createUserWithEmailAndPassword(email, password)
            .then((userCredential) => {
                const fim = Date.now();
                const tempoResposta = fim - inicio;
                console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
                var user = userCredential.user;
                history.push(`/list`);

            })
            .catch((error) => {
                 console.log(error.code);
                 console.log(error.message);
               
            });
    }

    return (

        <Container fluid="as" className="MainHeader">

            <Card className="text mx-auto " style={{ width: '25rem' }}>
                <Card.Body style={{ padding: '1.7rem' }}>
                    <Card.Title style={{ marginBottom: '2rem', textAlign: 'center', color: '#0d3c3f' }} > <h6> Faça login em sua conta</h6></Card.Title>

                    <Form style={{ marginBottom: '25px' }}>

                        <Form.Group >
                            <Form.Label>Email</Form.Label>
                            <Form.Control type="text" value={email}
                                maxLength="30"
                                onChange={e => setEmail(e.target.value)}
                                required
                            />
                        </Form.Group>


                        <Form.Group >
                            <Form.Label> Senha </Form.Label>
                            <Form.Control type="number"
                                maxLength="30"
                                value={password}
                                onChange={e => setPassword(e.target.value)}
                                required
                            />
                        </Form.Group>

                    </Form>
                    <Button className="Button2" block  onClick={() => loginUser()}  >Login</Button>

                    <div className="opcao">  OU  </div>

                    <Button className="Button2" block onClick={() => CadastrarUser()}>Cadastrar</Button>

                </Card.Body>
            </Card>

        </Container>
    )
}

// vue-app/src/views/Login.vue
<template>
  <div class="Conteiner">
    <b-card
      title="Faça login em sua conta"
      style="width: 25rem"
      class="mb-2 cardTitle"
    >
      <b-form style="margin-bottom: 1.5rem;margin-top: 1.5rem">

        <b-form-group id="input-group-1" label="Email" label-for="input-1">
        <b-form-input
          id="input-1"
          v-model="email"
          required
        ></b-form-input>
      </b-form-group>
      <br/>

      <b-form-group id="input-group-2" label="Senha" label-for="input-2">
      <b-form-input
          id="input-2"
          v-model="password"
          required
        ></b-form-input>
      </b-form-group>


      </b-form>
      <div>
      <b-button class="Button2"   @click="loginUser()" >Login</b-button>
      <div class="opcao">OU</div>
      <b-button  class="Button2"   @click="CadastrarUser()" >Cadastrar</b-button>
      </div>
    </b-card>
  </div>
</template>

<script>

import { firebase } from '@firebase/app'

export default {
  name: "Login",
  data() {
    return {
      email: "",
      password: "",
    };
  },
  methods: {

   loginUser() {
    const inicio = Date.now();
       firebase.auth().signInWithEmailAndPassword(this.email, this.password).then((user) => {
          this.$router.push("/list");
          const fim = Date.now();
          const tempoResposta = fim - inicio;
          console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
        }).catch(function (error) {
            // Handle Errors here.
            var errorCode = error.code;
            var errorMessage = error.message;
            if (errorCode === 'auth/wrong-password') {
                alert('Wrong password.');
            } else {
                alert(errorMessage);
            }
            console.log(error);
        });


   },


   CadastrarUser() {
  const inicio = Date.now();
  firebase.auth().createUserWithEmailAndPassword(this.email, this.password)
    .then((user) => {
      this.$router.push('/list');
      const fim = Date.now();
      const tempoResposta = fim - inicio;
      console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
    })
    .catch((error) => {
      console.log(error.code);
      console.log(error.message);
    });
}

  },
};
</script>


<style scoped>
.Conteiner {
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background: #F6F7F8;
}

 h4, .h4 {
    font-size: 1rem !important;
    font-weight: 400 !important;
}

.cardTitle {
  margin-bottom: 2rem;
  color: #0d3c3f;
  padding: 1rem;
}

.opcao{
  text-align: center;
  margin: 6px;
  font-size: 12px;
}

.Button2 {
  background-color: #0d3c3f !important;
  width: 100%;
  color: #FFFF;
}
</style>
