// angular-app/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { UserServiceService } from 'src/app/users/shared/user-service.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  email!: string;
  password!: string;

  constructor(private userService: UserServiceService, private router: Router) {}

  async login(): Promise<void> {
    const inicio = Date.now();
    try {
      const user = await this.userService.login(this.email, this.password);
      // Lógica adicional após o login bem-sucedido, como redirecionar para outra página
      this.router.navigate(['/list']);
      const fim = Date.now();
      const tempoResposta = fim - inicio;
      console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
      console.log('Login bem-sucedido!', user);
    } catch (error) {
      // Lidar com erros de login, como exibir uma mensagem de erro para o usuário
      console.error('Erro ao fazer login:', error);
    }
  }
  register(): void {
    const inicio = Date.now();
    this.userService.createUser(this.email, this.password)
      .then(() => {
        console.log('Usuário cadastrado com sucesso!');
        this.router.navigate(['/list']);

    const fim = Date.now();
    const tempoResposta = fim - inicio;
    console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
      })
      .catch(error => {
        console.error('Erro ao cadastrar usuário:', error);
      });

  }
}

<div class="conteiner">
  <div class="card" style="width: 25rem;">
    <h4 class="cardtitle" >Faça login em sua conta</h4>
    <form style=" padding: 1.5rem;">

      <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      </div>

      <div class="form-group">
        <label for="exampleInputPassword1">Senha</label>
        <input type="password" class="form-control" id="exampleInputPassword1">
      </div>

      <button type="submit" class="btn">Login</button>
      <p class="opcao">OU</p>
      <button type="submit" class="btn">Cadastrar</button>
    </form>
  </div>
</div>

// vue-padroes-app/src/views/Login.vue
<template>
  <div class="Conteiner">
    <b-card
      title="Faça login em sua conta"
      style="width: 25rem"
      class="mb-2 cardTitle"
    >
      <b-form style="margin-bottom: 1.5rem;margin-top: 1.5rem">

        <b-form-group id="input-group-1" label="Email" label-for="input-1">
        <b-form-input
          id="input-1"
          v-model="email"
          required
        ></b-form-input>
      </b-form-group>
      <br/>

      <b-form-group id="input-group-2" label="Senha" label-for="input-2">
      <b-form-input
          id="input-2"
          v-model="password"
          required
        ></b-form-input>
      </b-form-group>


      </b-form>
      <div>
      <b-button class="Button2"   @click="loginUser()" >Login</b-button>
      <div class="opcao">OU</div>
      <b-button  class="Button2"   @click="CadastrarUser()" >Cadastrar</b-button>
      </div>
    </b-card>
  </div>
</template>

<script>
//import DataController from "../Controller/Controller";
import DataFactory from "../Factory/Factory";
import DataBuilder from "../Builder/Builder";

export default {
  name: "Login",
  data() {
    return {
      email: "",
      password: "",
      factorys:[],
      builder: "",
    };
  },
  methods: {

   factory(){
      this.factorys = DataFactory.userFactory(this.email,this.password,"user");
   },

   Builder(){
      this.builder = DataBuilder.userBuilder();
   },

   loginUser() {
        const inicio = Date.now();
        this.factory();
        this.Builder();
        this.builder.loginBuilder(this.factorys.email,this.factorys.password)
        .then((user) => {
             this.$router.push("/list");
             console.log("login realizado com sucesso");
             const fim = Date.now();
            const tempoResposta = fim - inicio;
            console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
        }).catch(function (error) {
             console.log(error);
        });

   },


   CadastrarUser(){
        const inicio = Date.now();
        this.factory();
        this.Builder();
        this.builder.CadastrarBuilder(this.factorys.email,this.factorys.password)
        .then((user) => {
              this.$router.push('/list');
              console.log("cadastro realizado com sucesso");
              const fim = Date.now();
              const tempoResposta = fim - inicio;
              console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
        }).catch((error) => {
              console.log(error.code);
              console.log(error.message);
               
            });
   },

  },
};
</script>


<style scoped>
.Conteiner {
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background: #F6F7F8;
}

 h4, .h4 {
    font-size: 1rem !important;
    font-weight: 400 !important;
    text-align: center;
}

.cardTitle {
  margin-bottom: 2rem;
  color: #0d3c3f;
  padding: 1rem;
}

.opcao {
  text-align: center;
  margin: 6px;
  font-size: 12px;
}

.Button2 {
  background-color: #0d3c3f !important;
  width: 100%;
}
</style>>
