// angular-app/src/app/components/modal-excluir/modal-excluir.component.ts
import { Component, OnInit, TemplateRef, Input } from '@angular/core';
import { BsModalRef, BsModalService } from 'ngx-bootstrap/modal';
import { Tarefa } from 'src/app/tarefas/shared/tarefa';
import { TarefaService } from 'src/app/tarefas/shared/tarefa.service';

@Component({
  selector: 'app-modal-excluir',
  templateUrl: './modal-excluir.component.html',
  styleUrls: ['./modal-excluir.component.css']
})

export class ModalExcluirComponent implements OnInit {
  modalRef!: BsModalRef;
  @Input() item?: Tarefa;

  constructor(private modalService: BsModalService, private tarefaService: TarefaService) {}

  openModal(template: TemplateRef<any>) {
    this.modalRef = this.modalService.show(template);
  }

  ngOnInit(): void {}

  deleteItem(): void {
    const inicio = Date.now();
    if (!this.item || !this.item.key) {
      console.error('Item inválido para exclusão');
      return;
    }
    this.tarefaService.delete(this.item.key)
      .then(() => {
        console.log('Atividade excluída com sucesso!');
        this.modalRef.hide();
        const fim = Date.now();
        const tempoResposta = fim - inicio;
        console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
      })
      .catch(error => {
        console.error('Ocorreu um erro ao excluir a atividade:', error);
      });


  }
}

<button type="button" class="btn btn-success" id="show-btn" (click)="openModal(template)"><i class="bi bi-trash-fill"></i></button>

<ng-template #template>
  <div class="modal-header">
    <h4 class="modal-title pull-left">Excluir Atividade?</h4>
    <button type="button" class="close pull-right" aria-label="Close" (click)="modalRef.hide()">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="modal-body">
    Tem certeza de que deseja excluir a tarefa {{ item?.title }}?
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-danger" (click)="modalRef.hide()">Cancelar</button>
    <button type="button" class="btn btn-success" (click)="deleteItem()">Excluir</button>
  </div>
</ng-template>

// react-padroes-app/src/components/ModalExcluir/index.js
import React, { useState } from 'react';
import { Modal, Button } from 'react-bootstrap';
import DataController from "../../Controller/Controller";

export default function ModalExcluir(props) {

  const {id, descricao} = props;
  const [deleteAtivity, setDeleteAtivity] = useState(false);

  const deleteTutorial = () => {
    const inicio = Date.now();
    DataController.deletarAtividade(id)
        .then(() => {
          console.log("Deletado com sucesso!");
          setDeleteAtivity(false);
          const fim = Date.now();
          const tempoResposta = fim - inicio;
          console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
        })
        .catch((e) => {
          console.log(e);
        });
  }

  return (
    <>
      <Button variant="success" size="sm" onClick={(a) => setDeleteAtivity(true) }> <i className="far fa-trash-alt"></i></Button>

      <Modal show={deleteAtivity} onHide={() => setDeleteAtivity(false)}>

        <Modal.Header>
          <Modal.Title>Deletar atividade? </Modal.Title>
        </Modal.Header>

        <Modal.Body>
          Descrição: {descricao}
        </Modal.Body>

        <Modal.Footer>
          <Button variant="danger" onClick={() => setDeleteAtivity(false)}> Cancelar </Button>
          <Button variant="success" onClick={() => deleteTutorial()}>  Excluir </Button>
        </Modal.Footer>
      </Modal>
    </>
  );


}
