// react-app/src/components/ModalExcluir/index.js
import React, { useState } from 'react';
import { Modal, Button } from 'react-bootstrap';
import DataService from "../../services/service";

export default function ModalExcluir(props) {

  const {id, descricao} = props;
  
  const [deleteAtivity, setDeleteAtivity] = useState(false);

  const deleteTutorial = () => {
    const inicio = Date.now();

      DataService.delete(id)
        .then(() => {
          console.log("Deletado com sucesso!");
          setDeleteAtivity(false);
          const fim = Date.now();
          const tempoResposta = fim - inicio;
          console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
        })
        .catch((e) => {
          console.log(e);
        });


  }

  return (
    <>
      <Button variant="success" size="sm" onClick={(a) => setDeleteAtivity(true) }> <i className="far fa-trash-alt"></i></Button>

      <Modal show={deleteAtivity} onHide={() => setDeleteAtivity(false)}>

        <Modal.Header>
          <Modal.Title>Deletar atividade? </Modal.Title>
        </Modal.Header>

        <Modal.Body>
          Descrição: {descricao}
        </Modal.Body>

        <Modal.Footer>
          <Button variant="danger" onClick={() => setDeleteAtivity(false)}> Cancelar </Button>
          <Button variant="success" onClick={() => deleteTutorial()}>  Excluir </Button>
        </Modal.Footer>
      </Modal>
    </>
  );


}

// angular-padroes-app/src/app/components/modal-excluir/modal-excluir.component.ts
import { Component, OnInit, TemplateRef, Input } from '@angular/core';
import { BsModalRef, BsModalService } from 'ngx-bootstrap/modal';
import { Tarefa } from 'src/app/tarefas/shared/tarefa';
import { TarefaService } from 'src/app/tarefas/shared/tarefa.service';

@Component({
  selector: 'app-modal-excluir',
  templateUrl: './modal-excluir.component.html',
  styleUrls: ['./modal-excluir.component.css']
})
export class ModalExcluirComponent implements OnInit {
  modalRef!: BsModalRef;
  @Input() item?: Tarefa;

  constructor(private modalService: BsModalService, private tarefaService: TarefaService) {}

  openModal(template: TemplateRef<any>) {
    this.modalRef = this.modalService.show(template);
  }

  ngOnInit(): void {}

  deleteItem(): void {
    if (!this.item || !this.item.key) {
      console.error('Item inválido para exclusão');
      return;
    }
    const inicio = Date.now();
    this.tarefaService.delete(this.item.key)
      .then(() => {
        const fim = Date.now();
        const tempoResposta = fim - inicio;
        console.log(`O tempo de resposta foi de ${tempoResposta} milissegundos.`);
        console.log('Atividade excluída com sucesso!');
        this.modalRef.hide();
      })
      .catch(error => {
        console.error('Ocorreu um erro ao excluir a atividade:', error);
      });
  }
}
